/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as MedicamentsRouteImport } from './routes/medicaments'
import { Route as GardeRouteImport } from './routes/garde'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentsRoute = MedicamentsRouteImport.update({
  id: '/medicaments',
  path: '/medicaments',
  getParentRoute: () => rootRouteImport,
} as any)
const GardeRoute = GardeRouteImport.update({
  id: '/garde',
  path: '/garde',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carte': typeof CarteRoute
  '/garde': typeof GardeRoute
  '/medicaments': typeof MedicamentsRoute
  '/urgences': typeof UrgencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carte': typeof CarteRoute
  '/garde': typeof GardeRoute
  '/medicaments': typeof MedicamentsRoute
  '/urgences': typeof UrgencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carte': typeof CarteRoute
  '/garde': typeof GardeRoute
  '/medicaments': typeof MedicamentsRoute
  '/urgences': typeof UrgencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/carte' | '/garde' | '/medicaments' | '/urgences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/carte' | '/garde' | '/medicaments' | '/urgences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/carte'
    | '/garde'
    | '/medicaments'
    | '/urgences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarteRoute: typeof CarteRoute
  GardeRoute: typeof GardeRoute
  MedicamentsRoute: typeof MedicamentsRoute
  UrgencesRoute: typeof UrgencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urgences': {
      id: '/urgences'
      path: '/urgences'
      fullPath: '/urgences'
      preLoaderRoute: typeof UrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicaments': {
      id: '/medicaments'
      path: '/medicaments'
      fullPath: '/medicaments'
      preLoaderRoute: typeof MedicamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garde': {
      id: '/garde'
      path: '/garde'
      fullPath: '/garde'
      preLoaderRoute: typeof GardeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarteRoute: CarteRoute,
  GardeRoute: GardeRoute,
  MedicamentsRoute: MedicamentsRoute,
  UrgencesRoute: UrgencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
