// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcbneizljzrgmvoraxat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjYm5laXpsanpyZ212b3JheGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzODczNTcsImV4cCI6MjA5Njk2MzM1N30.TAQGWu1AHLTc5vONUek3BXFCgOh-1x63zZUyiiPs9DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});